### PR TITLE
Bump the version

### PR DESCRIPTION
**Pull request by nedbat**

### CODE REVIEW

**Comment by nedbat** [comment]
@singingwolfboy @feanil anyone care to kibbitz on an unimpeachable change?  BTW: I chose .0003 because we've made a few other changes before this one, but I didn't bother to count exactly.

**Comment by feanil** [comment]
:+1:

**Comment by singingwolfboy** [comment]
It looks like [the upstream django-staticfiles project is still at 1.2.1](https://github.com/jezdez-archive/django-staticfiles/blob/develop/staticfiles/__init__.py). Therefore, I suggest that we bump this to 1.2.2 to avoid ridiculous version strings.

I don't care about this very much. If you want to just merge as-is, I won't complain.

**Comment by nedbat** [comment]
The upstream is abandoned because it's been rolled into django.contrib.staticfiles.  We'll get back to the official Django code soon.  Going with this for now.  I like the "0003" because it's clear it's a serial number meant to tick over frequently.

**Pull request merged**
